version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/v1.16"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/v1.16"
    schedule:
      interval: "daily"