name: Artifacts

on:
  push:
    branches:
      - main

permissions:
  packages: write
  security-events: write

jobs:
  container-images:
    name: Container images
    runs-on: ubuntu-latest
    strategy:
      # Some older image builds may fail
      fail-fast: false
      matrix:
        fluentd:
          - v1.15-ruby3
          - v1.16

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/fluentd
          flavor: |
            latest = false
          tags: |
            type=raw,value=${{ matrix.fluentd }}-build.${{ github.run_number }}
            type=raw,value=${{ matrix.fluentd }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
        if: github.event_name == 'push'

      - name: Build and push BASE_IMAGE
        uses: docker/build-push-action@v5
        if: ${{ matrix.fluentd != 'v1.15-ruby3'}}
        with:
          context: ${{ matrix.fluentd }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: base

      - name: Build and push MINIMAL_IMAGE
        uses: docker/build-push-action@v5
        if: ${{ matrix.fluentd != 'v1.15-ruby3'}}
        with:
          context: ${{ matrix.fluentd }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: minimal

      - name: Build and push FULL_IMAGE
        uses: docker/build-push-action@v5
        if: ${{ matrix.fluentd != 'v1.15-ruby3'}}
        with:
          context: ${{ matrix.fluentd }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: full
      
      - name: Build and push v1.15
        uses: docker/build-push-action@v5
        if: ${{ matrix.fluentd == 'v1.15-ruby3'}}
        with:
          context: ${{ matrix.fluentd }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/fluentd:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
          format: "sarif"
          output: "trivy-results.sarif"
        if: github.event_name == 'push'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
        if: github.event_name == 'push'
