name: CI

on:
  pull_request:

jobs:
  container-images:
    name: Container images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fluentd:
          - v1.15-staging
          - v1.15-ruby3
          - v1.16

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/fluentd
          flavor: |
            latest = false
          tags: |
            type=raw,value=${{ matrix.fluentd }}-build.${{ github.run_number }}
            type=raw,value=${{ matrix.fluentd }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
        if: github.event_name == 'push'

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.fluentd }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
